fixed the built and checked issues
cjendres1/nhanes pull request #36
Opened 2023-09-09 14:06 UTC by ainilaha

1. Fixed build issues raised by MsSqlTools outside docker.
2. cleaned up the issues identified by running checks.

2023-09-10 14:13 UTC, cjendres1 requested changes
Made a few minor comments. The one issue that will impact CRAN checks is that you are now calling the DBI library, I believe that DBI needs to be added to the Imports.

2023-09-10 14:13 UTC, cjendres1 commented on DESCRIPTION
You both should add your info to the Authors field with role = 'aut'

2023-09-11 04:14 UTC, ainilaha commented on R/nhanes_tables.R
> +  if(is.numeric(year) & !is.na(.collection_date) & !is.na(.container_version)){
I will discuss it with Robert and see whether will include the Pre-pandemic and youth survey in further versions. But, we do not have them in the DB for now.

2023-09-11 04:15 UTC, ainilaha commented on README.md
> +The Docker container hosts the data, allowing for faster access and manipulation directly from the local Docker environment.
updated.

2023-09-11 04:15 UTC, ainilaha commented on DESCRIPTION
Added.

2023-09-11 04:16 UTC, ainilaha commented on R/db_util.R
> + return(DBI::dbGetQuery(cn(), sql))
added into suggests.

2023-09-11 10:56 UTC, cjendres1 approved these changes
This looks good!
We should next discuss routine testing.

2023-09-11 10:56 UTC, merged